master-nickname: 'HxppyFan'
master-twitch: 'hxppyfan'
master-discord: '752512860004810772'
discord-channel: '1092004008450850856'
stream-notification: "Ахуеть! **{streamerName}** начал стрем ахъахъах: 

https://www.twitch.tv/{streamerLogin}"
disc-bot-token: token
op-role: "1091972082436427796"

